defaults: &defaults
  token: pk.eyJ1IjoidGltcm9tYW5vd3NraSIsImEiOiJjaW04bG5rYnYwMjZmdjBsdTh1NjMyNWVrIn0.V1uutJECEvBov61VRx7Xog
  

development:
  <<: *defaults

test:
  <<: *defaults
  
production:
  <<: *defaults